// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// stepper_1sm //
// ----------- //

#define stepper_1sm_wrap_target 0
#define stepper_1sm_wrap 10
#define stepper_1sm_pio_version 1

static const uint16_t stepper_1sm_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa0e1, //  2: mov    osr, x
    0x6003, //  3: out    pins, 3
    0xa442, //  4: nop                           [4]
    0xa0e1, //  5: mov    osr, x
    0x6006, //  6: out    pins, 6
    0xb342, //  7: nop                           [19]
    0xe000, //  8: set    pins, 0
    0xa047, //  9: mov    y, osr
    0x008a, // 10: jmp    y--, 10
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program stepper_1sm_program = {
    .instructions = stepper_1sm_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = stepper_1sm_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config stepper_1sm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + stepper_1sm_wrap_target, offset + stepper_1sm_wrap);
    return c;
}
#endif

